version: "3"
services:
  neon-api:
    image: grafbase/neon-proxy:latest
    restart: always
    command: /usr/local/bin/proxy -c /server.crt -k /server.key --auth-backend=postgres --auth-endpoint=postgres://postgres:grafbase@postgres:5432/postgres --wss=0.0.0.0:4444
    ports:
      - "4444:4444"
    networks:
      - databases
  postgres:
    image: postgres:15
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "grafbase"
      POSTGRES_HOST_AUTH_METHOD: "md5"
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5432:5432"
    networks:
      - databases
  
networks:
  databases: null
